
language: python

python:
  - "3.5.2"
  
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
#command for creating a role and a database
  - psql -c "CREATE ROLE dario WITH SUPERUSER LOGIN PASSWORD 'riot';" -U postgres
  - psql -c 'CREATE DATABASE testride;' -U postgres
  - psql -c 'CREATE DATABASE ridemyway;' -U postgres
  
script: 
  #command to run tests
  - cd tests
  - nosetests  --with-coverage --cover-package=resources

after_success:
  - coveralls

# command to start postgresql
services:
  - postgresql